const http=require('http');
const {spawn}=require('child_process');
const {WebSocket}=require('ws');
const PUBLIC_PORT=Number(process.env.PORT||3000);
const APP_PORT=PUBLIC_PORT+1;
const TALA_WS_URL=process.env.TALA_WS_URL||'wss://web1.tala.ir/ws/';
const LIVE_MAX_AGE_MS=120000;
let liveMarket=null,liveAt=0,talaSocket=null,reconnectTimer=null,heartbeatTimer=null,lastError=null,messageCount=0;
const aliases={gram18:['geram18','gram18','geram_18','gram_18','18k','gold18'],gram740:['geram740','gram740','geram_740','gram_740','740'],gram21:['geram21','gram21','geram_21','gram_21'],gram22:['geram22','gram22','geram_22','gram_22'],usd:['usd','dollar','dollar_irt','usd_irt'],aed:['aed','dirham','emarat','aed_irt'],cad:['cad','canada','canadian_dollar','cad_irt'],eur:['eur','euro','eur_irt'],gbp:['gbp','pound','pound_irt'],chf:['chf','franc','swiss_franc'],cny:['cny','yuan','yuan_irt'],ounceUsd:['ounce','ounceusd','ounce_usd','ons','ons_usd'],mazanehJahani:['mazaneh-jahani','mazanehJahani','mazaneh_jahani'],emami:['sekkejad','emami','sekke_emami'],half:['sekkenim','half','nim'],quarter:['sekkerob','quarter','rob'],gerami:['sekkegrm','gerami','gerami_coin']};
function numberValue(v){if(v===null||v===undefined||v==='')return null;const s=String(v).replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[٬،]/g,',').replace(/,/g,'').trim();const n=Number(s);return Number.isFinite(n)?n:null}
function flatten(value,out={}){if(!value||typeof value!=='object')return out;if(Array.isArray(value)){for(const item of value)flatten(item,out);return out}for(const [key,val] of Object.entries(value)){const k=String(key).toLowerCase();if(val&&typeof val==='object'&&'value'in val){const n=numberValue(val.value);if(n!==null)out[k]=n}else{const n=numberValue(val);if(n!==null)out[k]=n;if(val&&typeof val==='object')flatten(val,out)}}return out}
function normalize(payload){const flat=flatten(payload),result={};for(const[target,keys]of Object.entries(aliases))for(const key of keys){const found=flat[String(key).toLowerCase()];if(found!==undefined){result[target]=found;break}}return result}
function accept(payload){const n=normalize(payload);if(!Object.keys(n).length)return false;liveMarket={...(liveMarket||{}),...n};liveAt=Date.now();lastError=null;return true}
function connectTala(){clearTimeout(reconnectTimer);try{if(talaSocket){try{talaSocket.removeAllListeners();talaSocket.close()}catch{}}talaSocket=new WebSocket(TALA_WS_URL,{headers:{Origin:'https://www.tala.ir','User-Agent':'Mozilla/5.0 NavabGold/1.0'},handshakeTimeout:15000,perMessageDeflate:false});talaSocket.on('open',()=>{lastError=null;clearInterval(heartbeatTimer);heartbeatTimer=setInterval(()=>{try{if(talaSocket?.readyState===1)talaSocket.ping()}catch{}},20000)});talaSocket.on('message',raw=>{messageCount++;let msg;try{msg=JSON.parse(raw.toString())}catch{return}if(accept(msg))return;for(const candidate of[msg?.data,msg?.result,msg?.payload,msg?.data?.data,msg?.data?.result,msg?.data?.payload])if(accept(candidate))break});talaSocket.on('error',e=>{lastError=e?.message||'Tala WebSocket error'});talaSocket.on('close',()=>{clearInterval(heartbeatTimer);reconnectTimer=setTimeout(connectTala,3000)})}catch(e){lastError=e?.message||'Tala WebSocket connection failed';reconnectTimer=setTimeout(connectTala,3000)}}connectTala();
const child=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:String(APP_PORT)},stdio:'inherit'});child.on('exit',code=>{if(code!==0)process.exit(code||1)});
const proxy=http.createServer((req,res)=>{const pathname=String(req.url||'').split('?')[0];if(pathname==='/api/market'&&req.method==='GET'){const fresh=Boolean(liveMarket&&liveAt&&Date.now()-liveAt<=LIVE_MAX_AGE_MS);const body=JSON.stringify({ok:fresh,source:'Tala.ir WebSocket',live:fresh,updatedAt:fresh?liveAt:null,market:fresh?liveMarket:{},error:fresh?null:(lastError||'No fresh live Tala.ir price message received yet'),debug:{socketConnected:Boolean(talaSocket&&talaSocket.readyState===1),messagesReceived:messageCount,lastPriceUpdateAt:liveAt||null}});res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(body);return}const upstream=http.request({hostname:'127.0.0.1',port:APP_PORT,path:req.url,method:req.method,headers:{...req.headers,host:`127.0.0.1:${APP_PORT}`}},r=>{const isHtml=String(r.headers['content-type']||'').includes('text/html');if(!isHtml){res.writeHead(r.statusCode,r.headers);r.pipe(res);return}const chunks=[];r.on('data',c=>chunks.push(c));r.on('end',()=>{let html=Buffer.concat(chunks).toString('utf8');if(pathname==='/'||pathname==='/index.html')if(html.includes('</body>'))html=html.replace('</body>','<script src="/market-strip.js?v=20260902" defer></script><script src="/category-strip-v2.js?v=20260902" defer></script><script src="/market-fallback.js?v=20260901" defer></script><script src="/storefront-settings-sync.js?v=20260901" defer></script></body>');if(pathname==='/admin'||pathname==='/admin.html')if(html.includes('</body>'))html=html.replace('</body>','<script src="/admin-site-settings.js?v=20260901" defer></script></body>');const headers={...r.headers,'content-length':Buffer.byteLength(html)};delete headers['content-encoding'];res.writeHead(r.statusCode,headers);res.end(html)})});upstream.on('error',()=>{if(!res.headersSent){res.writeHead(502,{'Content-Type':'text/plain; charset=utf-8'});res.end('Bad gateway')}});req.pipe(upstream)});proxy.listen(PUBLIC_PORT,'0.0.0.0',()=>console.log('[NAVAB] proxy listening on',PUBLIC_PORT,'-> app',APP_PORT));function shutdown(){try{child.kill('SIGTERM')}catch{}try{talaSocket?.close()}catch{}process.exit(0)}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);